# Generated by Django 4.1 on 2024-12-05 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0003_alter_newuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='newuser',
            name='lname',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
