# Generated by Django 4.1 on 2024-12-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0004_rename_name_newuser_fname_newuser_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='fname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='lname',
            new_name='Last_name',
        ),
    ]
