# Generated by Django 4.1 on 2024-12-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0005_rename_fname_newuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='Last_name',
        ),
    ]
