# Generated by Django 4.1 on 2024-12-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0007_rename_username_member_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='First_name',
            new_name='name',
        ),
    ]
