# Generated by Django 4.1 on 2024-12-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0008_rename_first_name_newuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='name',
            new_name='fname',
        ),
    ]
